apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: whiteboard-storage:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PASSWORD
          value: "redispass"
